// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoUlNJcFHF3vJvTyaOJ9HPCtsJ7ey7Kx8',
    appId: '1:339772638976:web:73e5282ce587b115f215e5',
    messagingSenderId: '339772638976',
    projectId: 'deneme-77e40',
    authDomain: 'deneme-77e40.firebaseapp.com',
    storageBucket: 'deneme-77e40.appspot.com',
    measurementId: 'G-R57ZCWYJLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOYf0wXzw11nfcO7OvFrDpy-plGeTyJOQ',
    appId: '1:339772638976:android:60a20b872ff5d7abf215e5',
    messagingSenderId: '339772638976',
    projectId: 'deneme-77e40',
    storageBucket: 'deneme-77e40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFHk2djqWNmHdI32Ft2vISCBnpvYEN4qk',
    appId: '1:339772638976:ios:72ce4c683e31c137f215e5',
    messagingSenderId: '339772638976',
    projectId: 'deneme-77e40',
    storageBucket: 'deneme-77e40.appspot.com',
    iosClientId: '339772638976-8sigjtun3tbfv1fg57ps8a0a13706vn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFHk2djqWNmHdI32Ft2vISCBnpvYEN4qk',
    appId: '1:339772638976:ios:72ce4c683e31c137f215e5',
    messagingSenderId: '339772638976',
    projectId: 'deneme-77e40',
    storageBucket: 'deneme-77e40.appspot.com',
    iosClientId: '339772638976-8sigjtun3tbfv1fg57ps8a0a13706vn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );
}
